services:
  nginx:
    build:
      context: .docker/nginx
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "${NGINX_PORT:-80}:80"
    volumes:
      - ./app:/var/www:cached
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php-fpm
      - redis
    networks:
      - chat_net

  php-fpm:
    build:
      context: .docker/php-fpm
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./app:/var/www:cached
      - ./.docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/docker-php-limit.ini
    depends_on:
      - postgres
      - redis
      - mercure
    networks:
      - chat_net

  postgres:
    image: postgres:14.13-alpine
    ports:
      - '${POSTGRES_PORT:-5433}:5432'
    volumes:
      - ./.docker/data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DATABASE:-postgres}
    networks:
      - chat_net

  redis:
    image: redis:7.2.4-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./.docker/data/redis:/data
    networks:
      - chat_net

  mercure:
    image: dunglas/mercure
    environment:
      DEBUG: "debug"
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_JWT_KEY:-jwt_key}
      MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_JWT_KEY:-jwt_key}
      MERCURE_EXTRA_DIRECTIVES: |-
        cors_origins "http://127.0.0.1"
        anonymous
    ports:
      - "9000:80"
    networks:
      - chat_net

networks:
  chat_net: